--
-- Addon       _mimi-name_obtained.lua
-- Author      marcob@marcob.org
-- StartDate   11/09/2017
-- Version     9
--
local addon, mimi = ...

mimi.db.minions["Acalan"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='From killing a skeleton or construct in Scarlet Gorge.',  }
mimi.db.minions["Aftershock"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Saint Taranis: Revered',  }
mimi.db.minions["Agnion Euzonos"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts).',  }
mimi.db.minions["Ahgnox"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["Airoldus"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ['life']='', ['death']='', ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Al"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="17", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Pelagic Order: Friendly',  }
mimi.db.minions["Alcander"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained for Credits under RIFT Store -> Pets -> Minions.', ['attracted attribute']='Assassination', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Anuxy"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Atragarians: Revered',  }
mimi.db.minions["Arcane Cannon"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ['diplomacy']='', ["harvesting"]="", ["dimension"]="", ['artifact']='', ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Archaeologist Herim"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Promo', ['details']='Complete \'Arclight Mastery\' Achievement during Arclight Infiltration Promo Week. Attracts Artifact Adventures.', ['attracted attribute']='Artifact', ["max no. of adventures attracted"]="2",  }
mimi.db.minions["Athelan the Fallen"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Taskmaster Atrophinius.',  }
mimi.db.minions["Atrophinius"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Fae Yule 8hr Minion Adventure unlocked with \'2014 Fae Yule Minion Adventure Pack\' from RIFT Store -> World Event.',  }
mimi.db.minions["Atrophinius the Festive"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Augustor"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="20", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='One and Many Quest in Ghar Station Tau (Tarken Glacier).',  }
mimi.db.minions["Aurora"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="20", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='Behold the Ascended at Ghar Station Mem in Goboro Reef',  }
mimi.db.minions["Azach"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Azumel"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='World Event', ['details']='From Autumn Harvest World Event 2014. Temporary found RIFT Store -> World Event',  }
mimi.db.minions["Baelnezum"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Valzor.',  }
mimi.db.minions["Bea"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Billows"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Artificer. Use \'Minions\' filter.', ['attracted attribute']='Dimension', ["max no. of adventures attracted"]="2",  }
mimi.db.minions["Birch"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Making Sense',  }
mimi.db.minions["Bitey"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Dropped from \'Invasive Species\' Hellbug lure during zone event in Silverwood for some1232.',  }
mimi.db.minions["Bloodroot the Feaster"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ['life']='', ["death"]="", ['hunting']='', ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Bloop"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Promo', ['details']='Comes with Infusion and Ultimate Nightmare Digitial Edition Packs',  }
mimi.db.minions["Bludfeng"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Pelagic Order: Decorated.',  }
mimi.db.minions["Breezy"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Onir: Honored',  }
mimi.db.minions["C1-0N3"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Apothecary. Use \'Minions\' filter.',  }
mimi.db.minions["Caeweth"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="10", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="10", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30",  }
mimi.db.minions["Captain Dagon"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="30", ["obtained"]="", ['details']='Summerfest',  }
mimi.db.minions["Carmine"] = { ["earth"]="", ["wind"]="", ["fire"]="20", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Cerulean Steel"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Weaponsmith. Use \'Minions\' filter.',  }
mimi.db.minions["Comet"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Artifact Set', ['details']='Rhen Coronation Memorabilia (65)',  }
mimi.db.minions["Connor"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="20", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='Walkabout Father Quest in Draumheim',  }
mimi.db.minions["Courage"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Cresaphin"] = { ["earth"]="17", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='Goboro Reef Instant Adventure. Rift Loot Bag. Also can be received from Nightmare Rift.',  }
mimi.db.minions["Crumpus"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Artifact Set', ['details']='Snow Names (65)',  }
mimi.db.minions["Cynthae"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Rift Loot Bag.',  }
mimi.db.minions["Dalkiros"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="17", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Rift drop. No specific Rift. Received from Rift Loot Bag.',  }
mimi.db.minions["Dargal"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Ghar: Honored',  }
mimi.db.minions["Dariah"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="17", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Dead Simon"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Pilfered Purses Achievement.',  }
mimi.db.minions["Deeps"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Last Of The Litter',  }
mimi.db.minions["Desecrated Lanaria"] = { ["earth"]="", ["wind"]="15", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="10", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="25", ['obtained']='Rift Store', ['details']='Requires Feilbokan: Revered',  }
mimi.db.minions["Dorald"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Reef Ramble',  }
mimi.db.minions["Doreen"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions', ['attracted attribute']='Artifact', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Drekanoth of Fate"] = { ["earth"]="12", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="12", ["death"]="12", ["hunting"]="12", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="12", ["assasination"]="12", ["max attribute score"]="24", ["max stamina"]="25", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Duke Arcarax"] = { ["earth"]="", ["wind"]="", ["fire"]="15", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='The devil you know',  }
mimi.db.minions["Eailziana"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ['death']='', ['hunting']='', ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Eelo"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Eliam"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Lockbox', ['details']='Chance drop from Lockboxes/Supply Crates',  }
mimi.db.minions["Ereetu"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/Mob Drop', ['details']='Normal mob on Ember Isle. Can also drop from Major Rift in Shimmersand.',  }
mimi.db.minions["Ewethanasia"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Ghar: Friendly',  }
mimi.db.minions["Face Pull"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions', ['attracted attribute']='Diplomacy', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Fang"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="17", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Floop"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Artifact Set', ['details']='Clubs of Bottomtown (63)',  }
mimi.db.minions["Fluffy"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Frederic Kain"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Lockbox', ['details']='Chance drop from Lockboxes/Supply Crates',  }
mimi.db.minions["Gakakhis"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='IA Drop', ['details']='During Autumn Harvest from the event IAs',  }
mimi.db.minions["Gambahl"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="15", ["death"]="20", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="5", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Valzor.',  }
mimi.db.minions["Garn"] = { ["earth"]="", ["wind"]="", ["fire"]="15", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Achievement', ['details']='All kobolds go to heaven',  }
mimi.db.minions["General Batua"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Tarken Glacier Puzzle drop.',  }
mimi.db.minions["Gil"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="17", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store/Fishing', ['details']='From \'Minion Starter Pack\'. Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Goldgrille"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Revered',  }
mimi.db.minions["Grace"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="17", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Greatfather Frost"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="15", ["harvesting"]="18", ["dimension"]="", ["artifact"]="15", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Grendelkhan"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="15", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Grish"] = { ["earth"]="", ["wind"]="7", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Gristlespitt"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Rift Store', ['details']='Requires Mages of Alittu: Decorated',  }
mimi.db.minions["Gruell"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Gurock"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="17", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='IA Drop', ['details']='Dropped from Freemarch Instant Adventure',  }
mimi.db.minions["Gust Front"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Rift Store', ['details']='Requires Mages of Alittu: Revered',  }
mimi.db.minions["Haligan the Pyretouched"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="10", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="15", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Taskmaster Atrophinius.',  }
mimi.db.minions["Herald Roklom"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Hexathel"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ['life']='', ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ['dimension']='', ["artifact"]="", ['assasination']='', ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Hogrol"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Killing mobs in Stillmoor at Crown Hill.',  }
mimi.db.minions["Hollowood"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Rift Store', ['details']='Requires Failbokan: Decorated',  }
mimi.db.minions["Hylas"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="17", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Decorated',  }
mimi.db.minions["Ich'kir"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Honored',  }
mimi.db.minions["Ikaras"] = { ["earth"]="17", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='Nightmare Rift drop. Received from Rift Loot Bag. Also found in Goboro Reef IA in Rift Loot Bag',  }
mimi.db.minions["Ilchorin"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Infernowl"] = { ["earth"]="", ["wind"]="18", ["fire"]="17", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='From \'Minion Starter Pack\'',  }
mimi.db.minions["Inquisitor Garau"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Revered',  }
mimi.db.minions["Ionraic"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='IA Drop', ['details']='Dropped from Instant Adventure Caches.',  }
mimi.db.minions["Ithmyr"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="17", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift I Cache drop.',  }
mimi.db.minions["Ivory"] = { ["earth"]="", ["wind"]="20", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Fae Yule 8hr Minion Adventure unlocked with \'2014 Fae Yule Minion Adventure Pack\' from RIFT Store -> World Event.',  }
mimi.db.minions["Ivy"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="20", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["IX-1 Defender"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Unchained',  }
mimi.db.minions["Jacenda Cassana"] = { ["earth"]="", ["wind"]="", ["fire"]="17", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='Nightmare Rift drop. Received from Rift Loot Bag. Also from Instant Adventures (Shimmersand/etc)',  }
mimi.db.minions["Jakub"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Lockbox', ['details']='Chance drop from Lockboxes/Supply Crates',  }
mimi.db.minions["Jari"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="17", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='From Bogling in Moonshade Highlands. Can also drop from Lesser Golems in the same zone.',  }
mimi.db.minions["Jasper"] = { ["earth"]="20", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Jilleen"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts).',  }
mimi.db.minions["Jineth"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="20", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="30", ['obtained']='Promo', ['details']='Complete \'Attractive Proposition\' Quest during Arclight Infiltration Promo Week. Attracts Artifact Adventures specific to the Promo Week', ['attracted attribute']='Artifact', ["max no. of adventures attracted"]="1",  }
mimi.db.minions["Jolly Hellbug"] = { ["earth"]="", ["wind"]="", ["fire"]="15", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='Fae Yule World Event 2016',  }
mimi.db.minions["Joloral Ragetide"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Kaerth"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="12", ["hunting"]="12", ["diplomacy"]="", ["harvesting"]="5", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="20", ['obtained']='Zone Event Drop',  }
mimi.db.minions["Kallos"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='From Ridgeline Stoneface in Crescent Ridge - Shimmersand (so probs random mob drop)',  }
mimi.db.minions["Keavy"] = { ["earth"]="", ["wind"]="17", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='World Event', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Kepple"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Can be fished up using Stan\'s Super Secret Lure.',  }
mimi.db.minions["Kiljurn"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Red Tide',  }
mimi.db.minions["Killthraxus"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Rift Store', ['details']='Requires Bailghol: Decorated',  }
mimi.db.minions["King Derribec"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Lockbox', ['details']='Chance drop from Lockboxes/Supply Crates',  }
mimi.db.minions["King Humbart"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Lockbox', ['details']='Chance drop from Lockboxes/Supply Crates',  }
mimi.db.minions["Kithlik"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Trudging Through The Tundra',  }
mimi.db.minions["Knifebeak"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Dropped from rare mob Koglok in Droughtlands',  }
mimi.db.minions["Kolmasveli"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Onir: Revered',  }
mimi.db.minions["Krass"] = { ["earth"]="", ["wind"]="", ["fire"]="17", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='From Instant Adventure in Silverwood (probably other IAs as well) and from Nightmare Rifts.',  }
mimi.db.minions["Kre'll"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Pelagic Order: Honored',  }
mimi.db.minions["Lamonrian"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Atragarians: Honored',  }
mimi.db.minions["Lecu the Claw"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="17", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Lil Reggie"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift Cache drop.',  }
mimi.db.minions["Living Vine Wall"] = { ["earth"]="17", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Lord Vyre"] = { ["earth"]="", ["wind"]="17", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift Cache drop.',  }
mimi.db.minions["Lucile"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minion', ['attracted attribute']='Dimension', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Lugglaga"] = { ["earth"]="", ["wind"]="", ["fire"]="17", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Rift Loot Bag.',  }
mimi.db.minions["Lyle"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Armorsmith. Use \'Minions\' filter.', ['attracted attribute']='Assassination', ["max no. of adventures attracted"]="2",  }
mimi.db.minions["Mael Salach"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='The once and the future dragon',  }
mimi.db.minions["Magmus"] = { ["earth"]="18", ["wind"]="", ["fire"]="17", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Friendly',  }
mimi.db.minions["Makirn"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Rift Loot Bag whilst PvPing.',  }
mimi.db.minions["Marile"] = { ["earth"]="17", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift Cache drop. Also drops from IAs (Freemarch/etc)',  }
mimi.db.minions["Mark"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="17", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Puzzle/Artifact', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time. Also from \'Wedding Gifts of Shadow Scion\' Artifact Set.',  }
mimi.db.minions["Martin"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minion', ['attracted attribute']='Harvesting', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Martrodraum"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="17", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Friendly',  }
mimi.db.minions["Mech Anik"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='Achievement', ['details']='From \'Capacitor Competency\' achievement gained during Arclight Ascendency Promo Weeks.',  }
mimi.db.minions["Michael Bringhurst"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="12", ["hunting"]="12", ["diplomacy"]="", ["harvesting"]="5", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="20", ['obtained']='Rift Store', ['details']='Requires Planar Defense Force: Revered',  }
mimi.db.minions["Milkweed"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Outfitter. Use \'Minions\' filter.', ['attracted attribute']='Harvesting', ["max no. of adventures attracted"]="2",  }
mimi.db.minions["Misty"] = { ["earth"]="", ["wind"]="17", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Atragarians: Friendly',  }
mimi.db.minions["Mitch"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="20", ["harvesting"]="", ["dimension"]="20", ["artifact"]="15", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='World Event', ['details']='From Summerfest World Event 2016. Temporary found RIFT Store -> World Event for Credits',  }
mimi.db.minions["Moltarr"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Pelagic Order: Decorated',  }
mimi.db.minions["Mongrok"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Artifact Set', ['details']='Bloodfire Soldier Kit (61)',  }
mimi.db.minions["Morid Finric"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Achievement', ['details']='Conqeuror: The Rhen of Fate Achievement. Bind on Pickup.',  }
mimi.db.minions["Mossclaw"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Rift Store', ['details']='Requires Saint Taranis: Decorated',  }
mimi.db.minions["Ms. Meles"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="12", ["death"]="12", ["hunting"]="12", ["diplomacy"]="", ["harvesting"]="12", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='World Event', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Mudthumper the Mulcher"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Muirden"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='From Summerfest World Event 2015. Temporary found RIFT Store -> World Event for Credits',  }
mimi.db.minions["Nado"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift. Received from Nightmare Rift IV in Rift Loot Bag.',  }
mimi.db.minions["Naveer"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="17", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='From \'Minion Starter Pack\'',  }
mimi.db.minions["Necrawler"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='From Autumn Harvest World Event 2014. Temporary found RIFT Store -> World Event',  }
mimi.db.minions["Nessie"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="17", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Nightbringer"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Part of \'2014 Fae Yule Minion Adventure Pack\' in RIFT Store.',  }
mimi.db.minions["Nipper"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='From \'Minion Starter Pack\'',  }
mimi.db.minions["Nixtoc"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="18", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Decorated',  }
mimi.db.minions["Noggol the Tainted"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="15", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="10", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="20",  }
mimi.db.minions["Noxie"] = { ["earth"]="17", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop.',  }
mimi.db.minions["Nyor'tothgylu"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="17", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Oblivia"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="20", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Omi"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Goboro Reef Puzzle as random drop from the chest after your first-time reward.',  }
mimi.db.minions["Opheline"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="17", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Onir: Friendly',  }
mimi.db.minions["Opie"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Vendor', ['details']='Tenebrian Mistery Box (SFP launch)',  }
mimi.db.minions["Orlan"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Chest Drop', ['details']='Chance drop from \'Hidden Chest\' and/or the rare mob Blightbread in Chronicle: Intrepid: Greenscale\'s Blight.',  }
mimi.db.minions["Ornipteryx"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["Patches"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="17", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Pay to Whinny"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Loyalty', ['details']='Gained from getting 1', ["attracted attribute"]="640", ['max no. of adventures attracted']='000 loyalty points into Silver Tier Loyalty.',  }
mimi.db.minions["Pebbles"] = { ["earth"]="12", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="12", ["artifact"]="12", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="20",  }
mimi.db.minions["Phanagos"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Pelagic Order: Revered',  }
mimi.db.minions["Pirex Flashfire"] = { ["earth"]="", ["wind"]="10", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="5", ["artifact"]="", ["assasination"]="", ["max attribute score"]="23", ["max stamina"]="20",  }
mimi.db.minions["Pizko"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Atragarians: Decorated.',  }
mimi.db.minions["Prince Kaliban"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Honored',  }
mimi.db.minions["Prince Tristaine"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="7", ["hunting"]="", ["diplomacy"]="17", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Una doesn\'t love you anymore',  }
mimi.db.minions["Prophet Ananke"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Evora@Camp Quagmire', ['details']='Requires Mages of Alitty: Revered',  }
mimi.db.minions["Pyrestorm"] = { ["earth"]="", ["wind"]="18", ["fire"]="17", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='Mob Drop', ['details']='Random drop from Rare mob: Pyrestorm in Goboro Reef',  }
mimi.db.minions["Qu'ella the Wretched"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Taskmaster Atrophinius.',  }
mimi.db.minions["Quaq"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Zone Event Drop', ['details']='Drops from Zone Event in Rift Loot Bag. Might be any NT zone', ['attracted attribute']=' but confirmed chance drop from \'The Leviathan\' zone event in Tyrant\'s Throne',  }
mimi.db.minions["Queen Zr'Bzz"] = { ["earth"]="", ["wind"]="17", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Dropped from Sharptalon Windwitch in Howling Plateau and Keenblade Machinist & Keenblade Millhand in Scarwood Reach.',  }
mimi.db.minions["Quetzie"] = { ["earth"]="", ["wind"]="20", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Ra'Aran of Fate"] = { ["earth"]="", ["wind"]="12", ["fire"]="12", ["water"]="12", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="12", ["harvesting"]="12", ["dimension"]="12", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="25", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Ranger Fahrand"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Rashboil"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Ravi"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Razorleaf Matriarch"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ['life']='', ["death"]="", ['hunting']='', ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Reginald"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Achievement', ['details']='A Prowed Moment',  }
mimi.db.minions["Rirnef"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="20", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='Questionable Allegiances from Finric at Port Scuddra in Tarken Glacier.',  }
mimi.db.minions["Ritualist Madina"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Roshin"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="17", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='IA Drop', ['details']='From Instant Adventures.',  }
mimi.db.minions["Rough Raptor"] = { ["earth"]="", ["wind"]="", ['fire']='', ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ['harvesting']='', ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ["max stamina"]="30", ['obtained']='Promo', ['details']='From Extra Life 2014 charity contest prize.',  }
mimi.db.minions["Rudy"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Part of \'2014 Fae Yule Minion Adventure Pack\' in RIFT Store.',  }
mimi.db.minions["Runald"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Crafted', ['details']='RIFT Store -> Crafting -> Runecrafter. Check \'Minions\' filter.', ['attracted attribute']='Hunting', ["max no. of adventures attracted"]="2",  }
mimi.db.minions["Rusila Dreadblade"] = { ["earth"]="", ["wind"]="", ["fire"]="15", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="20",  }
mimi.db.minions["Ryuu"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions', ['attracted attribute']='Hunting', ["max no. of adventures attracted"]="4",  }
mimi.db.minions["Salvarola"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Revered',  }
mimi.db.minions["Scarbite"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='The Dreaming Seas',  }
mimi.db.minions["Scarn"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Thedeor\'s Spear: Decorated',  }
mimi.db.minions["Scythe"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='From Autumn Harvest World Event 2014. Temporary found RIFT Store -> World Event',  }
mimi.db.minions["Seoras"] = { ["earth"]="20", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="5", ["artifact"]="", ["assasination"]="5", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Sharad X9"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="17", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Getting Ahead in Tarken',  }
mimi.db.minions["Shelath"] = { ["earth"]="18", ["wind"]="17", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift III Rift Loot Bag.',  }
mimi.db.minions["Shourloth"] = { ["earth"]="", ["wind"]="", ["fire"]="15", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="10", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Rift Store', ['details']='Requires Thedeor\'s Spear: Revered',  }
mimi.db.minions["Shuffles"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["Sienna"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Simulacrum of Nathairacha"] = { ["earth"]="7", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Rift Store', ['details']='Requires Bailghol: Revered',  }
mimi.db.minions["Sir Razerton"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="17", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="30", ['obtained']='Promo', ['details']='From Razer Naga Redemption Pack 2014',  }
mimi.db.minions["Skitters"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="7", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Fished up using Uncle Stan\'s Secret Lure or Lure of Planar Distortion.',  }
mimi.db.minions["Sleilun"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Valzor.',  }
mimi.db.minions["Slithers"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="20", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='Goboro Reef Story Line Quest: \'Skelf Stories\' obtained from the Atragarian Well.',  }
mimi.db.minions["Slobberjaw"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Fae Yule 8hr Minion Adventure unlocked with \'2014 Fae Yule Minion Adventure Pack\' from RIFT Store -> World Event.',  }
mimi.db.minions["Snerkle"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Fishing', ['details']='Gained through fishing with Lure of Planar Distortion/Uncle Stan\'s Super Secret Lure.',  }
mimi.db.minions["Snottongue"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="7", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Ghar: Revered',  }
mimi.db.minions["Snowball"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="18", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop/Fishing', ['details']='Drop from Scribe Nychea in the Crystal Depth cave in Iron Pine Peak. And from Uncle Stan\'s Secret Lure.',  }
mimi.db.minions["Speludelver"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["Spirit Kite"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="17", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Achievement', ['details']='From \'Master of the Wild\' achievement found under Achievements -> Zones -> RIFT -> Planetouched Wilds',  }
mimi.db.minions["Steamskin"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Drop from Sicklehorns at (6178', ['attracted attribute']=' 4967) in Stonefield',  }
mimi.db.minions["Stofie"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="20", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Quest', ['details']='Minion starter quest at (12761', ['attracted attribute']=' 11566) in Tempest Bay',  }
mimi.db.minions["Styxoris"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Onir: Decorated.',  }
mimi.db.minions["Sulfus"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="7", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Dream Walking. Also from Draumheim Puzzle reward bag.',  }
mimi.db.minions["Sundereth"] = { ["earth"]="", ["wind"]="15", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="10", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Swarmlord Khargroth"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ["max stamina"]="20", ['obtained']='World Event', ['details']='Summerfest',  }
mimi.db.minions["Tagonia"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="17", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Tas'toni"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="17", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='From Abyssal Commanders and Cabalists in Fortune\'s End in Meridian.',  }
mimi.db.minions["Taskmaster Atrophinius"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="15", ["harvesting"]="18", ["dimension"]="12", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from RIFT Store -> World Event during Autumn Harvest for 750 Credits (675 for Patrons).',  }
mimi.db.minions["Tasuil"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="15", ["artifact"]="15", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Tavanion"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="17", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["The Golden Devourer"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Special version of Senbora the Devourer open raid boss in The Dendrome at Greenscale\'s Crater. Only available during Fae Yule World Event.',  }
mimi.db.minions["The Hag of Gloamwood"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="7", ["hunting"]="", ["diplomacy"]="17", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Taskmaster Atrophinius.',  }
mimi.db.minions["The Nightstalker"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='World Event', ['details']='Gained from the Autumn Harvest Minion Adventure Chain that starts with Minion Card: Taskmaster Atrophinius.',  }
mimi.db.minions["The Nuclei"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Planar Defense Force: Decorated',  }
mimi.db.minions["Thexahel"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ['life']='', ["death"]="", ["hunting"]="", ['diplomacy']='', ['harvesting']='', ['dimension']='', ["artifact"]="", ["assasination"]="", ["max attribute score"]="0", ['max stamina']='', ['obtained']='Zone Event Drop', ['details']='Cracking Xarth\'s Skull',  }
mimi.db.minions["Tiller"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="17", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Rift or Mob drop from Silverwood.',  }
mimi.db.minions["Tobbler"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Tsathtosa"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Tewop"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="17", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Mob Drop', ['details']='Dropped from rare mob \'Gnarl Nighthunter\' in Gloamwood.',  }
mimi.db.minions["Twist"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="20", ["assasination"]="", ["max attribute score"]="20", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Shucking Shrimp',  }
mimi.db.minions["Tzul"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="7", ["max attribute score"]="25", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Requires Manugo League: Revered',  }
mimi.db.minions["Una"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="", ["life"]="17", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Onir: Friendly',  }
mimi.db.minions["Uriel Chuluun"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="17", ["assasination"]="18", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Puzzle', ['details']='Gained from Nightmare Tide Puzzle chest after 1st time.',  }
mimi.db.minions["Urista"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="18", ["artifact"]="", ["assasination"]="17", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Valzor"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> World Event during Autumn Harvest for 750 Credits (675 for Patrons).',  }
mimi.db.minions["Violet"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="17", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Friendly',  }
mimi.db.minions["Voldax"] = { ["earth"]="17", ["wind"]="", ["fire"]="", ["water"]="18", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Dropped from Nightmare Rift Cache.',  }
mimi.db.minions["Warboss Drak"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="18", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='PvP', ['details']='From Marauders Supply Cache (gained by winning Lvl 60+ PvP Warfronts)',  }
mimi.db.minions["Welt"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="17", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift/IA Drop', ['details']='Nightmare Rift drop. Also from Instant Adventure in Scarwood Reach + Goboro Reef',  }
mimi.db.minions["Wicket"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="7", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ['max stamina']='', ['obtained']='Quest', ['details']='The Eternal Weapon: A Sticky Wicket',  }
mimi.db.minions["Wilson"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="18", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Gained from RIFT Store -> Pets -> Minions',  }
mimi.db.minions["Xandill"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires The Ghar: Decorated',  }
mimi.db.minions["Xharlion"] = { ["earth"]="", ["wind"]="12", ["fire"]="", ["water"]="", ["life"]="17", ["death"]="", ["hunting"]="7", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='Hidden Minion', ['details']='Please refer to the \'Hidden Minion Cards\' tab for full information.',  }
mimi.db.minions["Xorixla"] = { ["earth"]="", ["wind"]="18", ["fire"]="", ["water"]="17", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift Cache.',  }
mimi.db.minions["Yarjos Mezrot"] = { ["earth"]="18", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="7", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Cerulean Rhenke: Decorated',  }
mimi.db.minions["Yoodipti"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="7", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="18", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Artifact Set', ['details']='Draum\'s Tropical Dreams (61)',  }
mimi.db.minions["Yulelogon"] = { ["earth"]="", ["wind"]="", ["fire"]="", ["water"]="", ["life"]="12", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="12", ["artifact"]="", ["assasination"]="12", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='World Event', ['details']='Fae Yule World Event 2014. Fae Yule 8hr Minion Adventure unlocked with \'2014 Fae Yule Minion Adventure Pack\' from RIFT Store -> World Event.',  }
mimi.db.minions["Zairatis"] = { ["earth"]="", ["wind"]="", ["fire"]="18", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="7", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='Achievement', ['details']='Takin\' Tarken in Tarken Glacier (for completing Octus Monastery story quest).',  }
mimi.db.minions["Zathral"] = { ["earth"]="", ["wind"]="17", ["fire"]="", ["water"]="", ["life"]="", ["death"]="18", ["hunting"]="", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="18", ["max stamina"]="20", ['obtained']='Rift Drop', ['details']='Nightmare Rift drop. Received from Nightmare Rift I and III.',  }
mimi.db.minions["Zebrayan"] = { ["earth"]="", ["wind"]="", ["fire"]="7", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="18", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="", ["assasination"]="", ["max attribute score"]="25", ["max stamina"]="20", ['obtained']='RIFT Store', ['details']='Requires Atragarians: Decorated',  }
mimi.db.minions["Zendi"] = { ["earth"]="", ["wind"]="7", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="15", ["diplomacy"]="", ["harvesting"]="", ["dimension"]="", ["artifact"]="15", ["assasination"]="17", ["max attribute score"]="24", ["max stamina"]="30", ['obtained']='RIFT Store', ['details']='Obtained as part of \'The Wilds Pack\' available on RIFT Store -> Services', ['attracted attribute']=' Glyph website or via Steam.',  }
mimi.db.minions["Zephyr"] = { ["earth"]="", ["wind"]="12", ["fire"]="", ["water"]="", ["life"]="", ["death"]="", ["hunting"]="", ["diplomacy"]="12", ["harvesting"]="", ["dimension"]="", ["artifact"]="12", ["assasination"]="", ["max attribute score"]="24", ["max stamina"]="20",  }
